### ISSUE TITLE
hasMany value show a blank rectangle

### ISSUE THREAD

**Issue by GCorbel** [iStefo/ember-select-2#107]
Hello,

I have this simple selector : 

    {{select-2
        content=skills
        value=choosedSkills
        multiple=true
    }}

With this controller : 

    export default Ember.Controller.extend
      choosedSkills: (->
        @model.get('skills')
      ).property('choosedSkills')
      skills: (->
        @store.findAll 'skill'
      ).property('skills')

I think all skills of the model should be assigned but I have this result : 

![capture du 2015-06-27 13 53 48](https://cloud.githubusercontent.com/assets/1296201/8393215/17129e74-1cd4-11e5-985c-7fbe86817059.png)

When I try this : 

    export default Ember.Controller.extend
      choosedSkills: (->
        [{name: 'test', description: 'test'}]
      ).property('choosedSkills')
      skills: (->
        @store.findAll 'skill'
      ).property('skills')

It works.

Does ember-select-2 works with hasMany associations ?

**Comment by abobwhite** [comment]
@GCorbel I created an issue for this last week with the same issue: #105. I haven't heard anything back but looking through the code, it appears that ember-select-2 does not currently support hasMany because it setting the array instead of adding/removing from it which throws a console error seen in #105. If you open your console and are seeing this read-only error, you should go ahead and add your info to #105 and close this issue.

**Comment by vst** [comment]
Confirmed. Furthermore, if the value is a property of a DS object, the two way binding is broken, too.

**Comment by GCorbel** [comment]
It works now.

**Comment by abobwhite** [comment]
How can it work now? There have been no commits to this repo since before you even opened this issue......

@GCorbel

**Comment by GCorbel** [comment]
I saw. It maybe because of an update of ember...

**Comment by yaapis** [comment]
Same issue with ember 1.13.3 and ember data 1.13.5

**Comment by angouleme** [comment]
for everyone getting similar error (select2 with multiple option and hasMany), in last comment of this issue: https://github.com/iStefo/ember-select-2/issues/105 I've posted a workaround that worked quite well for me.
