### ISSUE TITLE
opts is not defined, addon broken with select2 3.5.3

### ISSUE THREAD

**Issue by jcope2013** [iStefo/ember-select-2#121]
oddly the new point release seem to have broken my code that looked like this, reverting back to 3.5.2 worked

```
{{select-2
        placeholder="Select a user"
        value=chosenUser
        typeaheadSearchingText="Searching users"
        typeaheadNoMatchesText="No users found for '%@'"
        typeaheadErrorText="Loading failed: %@"
        optionLabelPath="userName"
        query="queryUsers"
      }}
```

https://github.com/select2/select2/releases/tag/3.5.3

**Comment by kevin-brown** [comment]
This is a known bug in 3.5.3, a new 3.5.4 release is being cooked up to fix the issue.

https://github.com/select2/select2/issues/3694
