### ISSUE TITLE
Data from API is not showing on Hierarchical JSON Dropdown

### ISSUE THREAD

**Issue by jigneshchudasama05** [iStefo/ember-select-2#142]
I followed your example of Hierarchical JSON, in that you are passing data from ember-data, its working fine, but I want to show data which is coming from the API, not the ember-data.
I have formatted the JSON at the API as required but still not displaying the data. 

Any help? or anything that I missed?

**Comment by jigneshchudasama05** [comment]
Any update?

**Comment by iStefo** [comment]
Hi! Sorry I can't help you in this case. Make sure that you follow the examples (or tests) and make sure that you got any identifiers (optionValuePath) etc. right.
