### ISSUE TITLE
Typeahead and slow queries

### ISSUE THREAD

**Issue by martinmaillard** [iStefo/ember-select-2#40]
As expected, typeahead mode sends the `query` action for each letter typed (even the empty string). With a lot of data, the first requests sent to the server (with less letters to filter the results) will take a lot longer than the next ones. Now if a request is resolved (`deferred.resolve`) after a value has been selected by the user, the value is unselected and disappears from the field.

It feels like, when multiple `query` actions are sent, only the data coming from the last one should be processed by `ember-select-2`. I'm not sure if it is the concern of the library, or of the user implementing  the `query` action. What do you think ?

**Comment by iStefo** [comment]
You are correct, the component should only process the last promise issued. Additionally, previous promises could be resolved (to `null` maybe?) so that in theory, the developer could check if the value is still needed by the component.

It might take me some time to look into the exact behaviour, but the fix should be quite easy from there on. Thanks for letting me know!

**Comment by DVG** [comment]
In a similar vein, it'd be nice to optionally be able to stop the component from firing queries while the user is still typing, as it's just wasted queries on the backend

I have something like this implemented in a simple search box component to achieve that:

```javascript
export default Ember.Component.extend({
  delay: 500
  q: "" // the bound search property
  term: "" // the internal search term
  search: (function() {
    var min, term, timer;
    timer = null;
    term = this.get('term');
    min = this.get('searchMinimum');
    clearTimeout(timer);
    if (term.length >= min || term.length === 0) {
      return timer = setTimeout((function(_this) {
        return function() {
          return _this.set('q', term);
        };
      })(this), this.get('delay'));
    }
  }).observes('term')
});
```
