### ISSUE TITLE
Placeholder doesn't work

### ISSUE THREAD

**Issue by gopeter** [iStefo/ember-select-2#43]
I'm using `ember-select-2` in my Ember app and it works really great, thank you so much for that! But the placeholder doesn't work for me. It's just empty.

I'm using:
- Ember 1.9.1
- Ember Data 1.0.0-beta.14.1
- Handlebars 2.0
- jQuery 1.11.2
- ember-select-2 1.1.1-beta1

That's my code:
````
{{select-2
  cssClass="uk-width-1-1"
  content=sortedRequests
  value="selectedRequest"
  optionLabelPath="title"
  placeholder="Choose some Pizzas"
}}
````
And that's how it's look like:

![bildschirmfoto 2015-01-09 um 17 01 54](https://cloud.githubusercontent.com/assets/1242960/5682570/3e81f064-9821-11e4-8642-a17864ea61dc.png)

Searching in DOM for "Choose some Pizzas" returns in zero results. 

Any ideas? :)

**Comment by iStefo** [comment]
This is just guessing, but you used "selectedRequests" as a String, which is probably not what you want to. Does this solve the problem?

**Comment by gopeter** [comment]
Oh, you're right :D
Thanks a lot!
