### ISSUE TITLE
select-2 input keypress delay

### ISSUE THREAD

**Issue by kevinjalbert** [iStefo/ember-select-2#45]
I'm curious if there is a possibility to have some built-in functionality to delay the keypresses from triggering the query filtering? 

Right now the select-2 component is sending server queries on every keypress (Ideally I'd like to delay it a bit to reduce the number of outward queries). It could be possible that I am overlooking something?

**Comment by iStefo** [comment]
If you want to reduce the number of calls to your backend, please have a look at debounce (no *immediate*) and throttle (with *trailing*). This goes beyond the use of this component and will not be implemented in this component. I hope you will understand that decision.

**Comment by kevinjalbert** [comment]
Thank you for the suggestion on using the *debounce*. That was exactly what I was looking for.
