### ISSUE TITLE
Upgrade project to use ember-cli 0.1.6

### ISSUE THREAD

**Issue by iStefo** [iStefo/ember-select-2#49]
Carefully not overwriting any customisations, but not forgetting any required changes.

**Comment by ryanjm** [comment]
I'm trying to get `ember-select-2` setup in an Ember cli project using `0.1.7`.

Do you know the steps involved with getting this project updated? I'd like to get this working in the next few days and I'd be willing to create a PR to help out. I haven't looked at what it would take yet, but if you could give me a quick 5 min outline that'd save me an hour of figuring things out.

**Comment by iStefo** [comment]
Is there anything not working with this version of ember-select-2?

**Comment by ryanjm** [comment]
Maybe I just missed a step in the install process.

I did `npm install ember-select-2 --save-dev` and then `ember g ember-select-2`. But that gave me:

```
version: 0.1.7
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  not-cached git://github.com/ivaynberg/select2.git#*
  resolved git://github.com/ivaynberg/select2.git#3.5.2
Installed browser packages via Bower.
```

I even tried `ember install:addon ember-select-2` but that gave me similar output.

I'm not sure what else I need to do, but when I tried using `select-2` in my view it gives me:

```
... Handlebars error: Could not find property 'select-2' on object ...
```

What am I missing?

**Comment by ryanjm** [comment]
Looks like I forgot to restart my local server. Thanks.

**Comment by iStefo** [comment]
ember-cli 0.2.0 is ahead, I would suggest making an update once it's released

**Comment by iStefo** [comment]
Done, upgraded to 0.2.3
