### ISSUE TITLE
Allow Clear doesn't seem to be working

### ISSUE THREAD

**Issue by jcope2013** [iStefo/ember-select-2#52]
you can see it on the example on the site (https://istefo.github.io/ember-select-2/#/examples), allow-clear doesn't seem to be working properly as no clear button is displayed when the select box has a selection.

```{{select-2
    content=pizzas
    value=favouritePizza
    placeholder="Choose your pizza"
    allow-clear=true
}}```

it says

"By specifying the allow-clear option, you determine whether or not a clear button is displayed when the select box has a selection."

any tips?

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

https://github.com/istefo/ember-select-2

[ml]: https://github.com/ivaynberg/select2#mailing-list

**Comment by iStefo** [comment]
Thanks for dropping this issue, the documentation is bogus and it's meant to read `allowClear=true`. I updated the docs (will be published on the next release)
