### ISSUE TITLE
ember install:addon ember-select-2: The globPattern "undefined" did not match any files, so no file updates will be made.

### ISSUE THREAD

**Issue by lolmaus** [iStefo/ember-select-2#57]
```
$ ember install:addon ember-select-2
version: 0.1.7
Installed packages for tooling via npm.
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  not-cached git://github.com/ivaynberg/select2.git#*
  resolved git://github.com/ivaynberg/select2.git#3.5.2
Installed browser packages via Bower.
Installed addon package.
$
```

**Comment by iStefo** [comment]
I am really not sure why this is happening. However, the package installs fine and also includes the bower dependency as usual.

It seems like this issue was fixed recently and should not occur with future versions of ember-cli: https://github.com/ember-cli/ember-cli/issues/3142

**Comment by trabus** [comment]
Sorry about this, it was happening with any blueprint that didn't have files in it. The good news is, it was a benign warning, and didn't affect the install process. And the even better news is that it's gone as of ember-cli 0.1.13. :)
