### ISSUE TITLE
with firefox it is always disabled

### ISSUE THREAD

**Issue by francescabarbazeni87** [iStefo/ember-select-2#69]
Hi guys,

If I used this component in Firefox it is always disabled.
I have tried both enabled='enabled' and enabled=true.

THere is a solution?

**Comment by francescabarbazeni87** [comment]
the problem is in the version 1.2.0, the 1.1.1-beta1 works well.

**Comment by iStefo** [comment]
I could not reproduce this problem. You can try out version 1.3.0 released today, if you want. If there still is a problem, please tell me so we can solve this once and for all.
