### ISSUE TITLE
The version published to npm does not contain the htmlbars 1.0 compat Fix

### ISSUE THREAD

**Issue by alexBaizeau** [iStefo/ember-select-2#80]

**Comment by alexBaizeau** [comment]
Here is the link to the fix https://github.com/iStefo/ember-select-2/blob/master/addon/components/select-2.js#L71

I would suggest to try to publish a version 1.2.1

**Comment by f3ndot** [comment]
:+1:

**Comment by f3ndot** [comment]
Looks like it's available in `1.2.0` from npm

**Comment by alexBaizeau** [comment]
Oooops, sorry for the noise
