### ISSUE TITLE
Getting 'A helper named 'select-2' could not be found'

### ISSUE THREAD

**Issue by Jordan4jc** [iStefo/ember-select-2#93]
After trying to install and use select-2 I'm seeing this error in my console.

After I installed it using the default syntax `ember install ember-select-2`

I also had this error after NPM finished it's job

`The 'ember generate' command requires an entity name to be specified. For more details, use 'ember help'.`

**Comment by Jordan4jc** [comment]
Fixed by running `ember generate ember-select-2`

Which really should be added into the setup instructions just in case

**Comment by toovy** [comment]
I think

    ember install ember-select-2

is automatically running this, but there seems to be an error that prevents it to do so.

    The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

So I my eyes this is an installation issue and not a documentation issue.
